---
formatter: markdown table
version: ">= 0.16.0, < 1.0.0"

sort:
  enabled: true
  by: required

settings:
  # Only use Terraform Configuration for versions
  lockfile: false
  read-comments: false

output:
  file: README.md
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    {{ .Content }}
    <!-- END_TF_DOCS -->
