---
name: Pull Request

on:
  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: write
  issues: write
  checks: write
  pull-requests: write

jobs:
  terraform-ci:
    # This job name must match the name of call called Workflow in order for
    # the name to successfully match any required status checks within the
    # branch protections
    name: Terraform CI
    uses: ./.github/workflows/terraform-ci.yaml
    secrets: inherit
